export const styles: Record<string, React.CSSProperties> = {
    container: {
      backgroundColor: '#0b0f19',
      color: '#cbd5e1',
      fontFamily: 'sans-serif',
    },
    main: {
      maxWidth: '80rem', // max-w-7xl
      marginLeft: 'auto',
      marginRight: 'auto',
      paddingLeft: '1rem',
      paddingRight: '1rem',
      paddingTop: '1.5rem',
      paddingBottom: '1.5rem',
      display: 'flex',
      flexDirection: 'column',
      gap: '1.25rem',
    },
    chartWrapper: {
      width: '100%',
    },
    ledgerSegment: {
      backgroundColor: '#111827',
      borderRadius: '0.75rem',
      border: '1px solid #1f293d',
      boxShadow: '0 8px 32px rgba(0, 0, 0, 0.5)',
      overflow: 'hidden',
    },
    headerPanel: {
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
      paddingTop: '1.25rem',
      paddingBottom: '1.25rem',
      borderBottom: '1px solid #1f293d',
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'between',
      flexWrap: 'wrap',
      gap: '0.75rem',
      backgroundColor: '#141d2f',
    },
    titleWrapper: {
      display: 'flex',
      flexDirection: 'column',
    },
    title: {
      fontSize: '1rem',
      fontWeight: 600,
      color: '#ffffff',
      letterSpacing: '-0.025em',
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      margin: 0,
    },
    titleIndicator: {
      width: '0.375rem',
      height: '1rem',
      backgroundColor: '#00d09c',
      borderRadius: '9999px',
      display: 'inline-block',
    },
    subtitle: {
      fontSize: '0.75rem',
      color: '#64748b',
      marginTop: '0.125rem',
      fontWeight: 500,
      marginBottom: 0,
    },
    badge: {
      backgroundColor: '#1e293b',
      border: '1px solid #334155',
      fontSize: '10px',
      paddingLeft: '0.625rem',
      paddingRight: '0.625rem',
      paddingTop: '0.25rem',
      paddingBottom: '0.25rem',
      borderRadius: '4px',
      fontWeight: 'bold',
      letterSpacing: '0.05em',
      color: '#00d09c',
      textTransform: 'uppercase',
    },
    tableWrapper: {
      overflowX: 'auto',
    },
    table: {
      width: '100%',
      borderCollapse: 'collapse',
      textAlign: 'left',
      fontSize: '13px',
      tableLayout: 'auto',
    },
    th: {
      paddingTop: '0.75rem',
      paddingBottom: '0.75rem',
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
      fontWeight: 600,
      letterSpacing: '0.05em',
      fontSize: '11px',
      textTransform: 'uppercase',
      color: '#64748b',
      borderBottom: '1px solid #1f293d',
      backgroundColor: 'rgba(20, 29, 47, 0.6)',
    },
    thRight: {
      textAlign: 'right',
    },
    td: {
      paddingTop: '0.75rem',
      paddingBottom: '0.75rem',
      paddingLeft: '1.5rem',
      paddingRight: '1.5rem',
      borderBottom: '1px solid rgba(31, 41, 61, 0.3)',
      verticalAlign: 'middle',
    },
    tdIsin: {
      fontFamily: 'monospace',
      fontSize: '11px',
      color: '#475569',
    },
    tdName: {
      fontWeight: 600,
      letterSpacing: '0.025em',
      color: '#ffffff',
    },
    tdClass: {
      color: '#64748b',
      fontWeight: 500,
      fontSize: '0.75rem',
    },
    classSpan: {
      backgroundColor: '#1e293b',
      paddingLeft: '0.5rem',
      paddingRight: '0.5rem',
      paddingTop: '0.125rem',
      paddingBottom: '0.125rem',
      borderRadius: '4px',
      border: '1px solid rgba(51, 65, 85, 0.4)',
      color: '#94a3b8',
    },
    tdWeightCurrent: {
      textAlign: 'right',
      color: '#94a3b8',
      fontFamily: 'monospace',
      fontWeight: 500,
    },
    tdWeightTarget: {
      textAlign: 'right',
      color: '#ffffff',
      fontWeight: 'bold',
      fontFamily: 'monospace',
    },
    tdVariance: {
      textAlign: 'right',
      fontFamily: 'monospace',
      fontWeight: 'bold',
      fontSize: '12px',
    },
    pill: {
      display: 'inline-block',
      paddingLeft: '0.5rem',
      paddingRight: '0.5rem',
      paddingTop: '0.125rem',
      paddingBottom: '0.125rem',
      borderRadius: '4px',
      textAlign: 'center',
      minWidth: '70px',
    }
  };
  